version: "2"

services:
  protection_proxy:
    restart: unless-stopped
    image: casestudyintrusiondetection/protective_reverse_proxy:development
    container_name: protection_proxy
    volumes:
    #  - ./my-ssl.key:/etc/ssl/private/self_sslkey.pem:ro
    #  - ./my-ssl.pem:/etc/ssl/certs/self_sslcert.pem:ro
    #  - ./models/dummy:/protection/model/:ro
      - ./models/RealModels:/protection/model/:ro
    environment: 
      - BLOCK_CRAWLING=true # 'false', 'true'
      - BLOCK_TYPES= # one or multiple separated by ',' of: sql,xss,tampering,execution,disclosure,overflows,encryption,cve,redirect
      - ALLOW_TYPES= # one or multiple separated by ',' of:  sql,xss,tampering,execution,disclosure,overflows,encryption,cve,redirect
      - APPROACH_USE=lda,nn # 'lda', 'nn' or 'lda,nn' 
      - APPROACH_CONNECTOR=or # 'and', 'or'
      - MAIL_HOST= # hostname of a mailserver (smtp)
      - MAIL_PORT=587 # START TLS port of the server
      - MAIL_USERNAME= # username to access the server
      - MAIL_PASSWORD= # passwort to access server
      - MAIL_FROM= # sender of the emails
      - MAIL_TO= # receiver of the emails
      - SEND_DAILY_REPORT=true # true,false
      - SEND_EMERGENCY=true # true,false
      - ALLOW_AFTER_CAPTCHA=true # true,false
    ports:
      - "80:80"
      - "443:443"
  system_to_protect:
    container_name: system_to_protect
    restart: unless-stopped
    image: kimbtechnologies/kimb_forms_project:latest
    environment:
      - CONF_site_hosturl=
      - CONF_site_pagename=KIMB-Forms-Project
      - CONF_site_footercontent=Dummy to protect
      - CONF_captcha_poll=false
      - CONF_captcha_new=false
      - CONF_texts_enablePoll=false
      - CONF_texts_enableNew=true
      - CONF_texts_textPoll=Ich bin mit den Datenschutzrichtlinien ... einverstanden!
      - CONF_texts_textNew=Ich bin mit den AGB des Anbieters einverstanden!
      - CONF_cookiebanner=false
      - CONF_newpollmailto=test@example.com # admin mail, get mail when a poll is created
      - CONF_submissions_enabled=false # query for poll submissions by mail
      - CONF_submissions_captcha=true # query needs captcha
      - CONF_submissions_mailValidate=^\S+@\S+\.\S+$$ # query mail address validation
      - SMTP_SERVER= # the mail server host (used for admin notification mails)
      - SMTP_PORT= # the port to deliver mails (587 for starttls or 465 for tls)
      - SMTP_USER= # the username for the mail server
      - SMTP_PASS= # the password for the mail server